#pragma once

#include "./TEconomicReportReceiverBaseConfiguration.hpp"
#include "./TEconomicReportReceiverTypeCode.hpp"

#include "../Common/SourceCodeModel/IncrementHeaderInclusionBalance.hpp"

namespace Prototype52
{
   // See the config file for more info.

   class TEconomicReportReceiverFactoryConfiguration
   {
#if( /* {public DataTypeCode}. */ 1 )

      //
      public: TEconomicReportReceiverTypeCode DataTypeCode;

#endif
#if( /* {public DataTypeConfiguration}. */ 1 )

      //
      public: ::std::unique_ptr< TEconomicReportReceiverBaseConfiguration > DataTypeConfiguration;

#endif

#if( /* {public} Instance default constructor. */ 1 )

      //

      public: explicit TEconomicReportReceiverFactoryConfiguration();

#endif
#if( /* {private} Instance copy constructor. */ 1 )

      //

      private: explicit TEconomicReportReceiverFactoryConfiguration
         ( TEconomicReportReceiverFactoryConfiguration const & source
         );

#endif
#if( /* {(public)} Instance destructor. */ 1 )

      // Could be autogenerated.

#endif
#if( /* {private operator =}. */ 1 )

      //

      private: TEconomicReportReceiverFactoryConfiguration & operator =
         ( TEconomicReportReceiverFactoryConfiguration const & source
         );

#endif

#if( /* {public Validate}. */ 1 )

      // yg? This might need a parameter specifying configuration extraction state. Or better add a method with that parameter to the helpers.

      public: void Validate() const;

#endif
   };
}
