#pragma once

#include "./TEconomicReportReceiverViaTcpBaseConfiguration.hpp"

#include "../Common/SourceCodeModel/IncrementHeaderInclusionBalance.hpp"

namespace Prototype52
{
   // See the config file for more info.

   class TNewsHubEconomicIndicatorReceiverConfiguration :
      public TEconomicReportReceiverViaTcpBaseConfiguration
   {
#if( /* //{public TradingSignalsMap}. */ 1 )

      ////
      //public: ::std::map< ::Common::DataStructures::TDataBuffer, int > TradingSignalsMap;

#endif
#if( /* {public SocketDataBufferInitialCapacity}. */ 1 )

      //
      public: int SocketDataBufferInitialCapacity;

#endif
#if( /* //{public SocketDataBufferCapacityMaxLimit}. */ 1 )

      ////
      //public: int SocketDataBufferCapacityMaxLimit;

#endif
#if( /* {public EconomicIndicatorIdAsString}. */ 1 )

      //
      public: ::std::string EconomicIndicatorIdAsString;

#endif
#if( /* {public EconomicIndicatorValueMultiplier}. */ 1 )

      //
      public: double EconomicIndicatorValueMultiplier;

#endif

#if( /* {(public)} Instance default constructor. */ 1 )

      // Could be autogenerated.

#endif
#if( /* //{(private)} Instance copy constructor. */ 1 )

      // Cannot be autogenerated.

#endif
#if( /* {(public)} Instance destructor. */ 1 )

      // Could be autogenerated.
      // {virtual}.

#endif
#if( /* //{(private) operator =}. */ 1 )

      // Cannot be autogenerated.

#endif

#if( /* {public Validate}. */ 1 )

      // yg? This might need a parameter specifying configuration extraction state. Or better add a method with that parameter to the helpers.
      // TODO 3 yg? If I implement this method I will need to make it {virtual}.

      public: void Validate() const;

#endif
   };
}
