#pragma once

#include "./TPeerStrategyBaseConfiguration.hpp"
#include "./TSecondaryPeerStrategyPositionConfiguration.hpp"

#include "../Common/SourceCodeModel/IncrementHeaderInclusionBalance.hpp"

namespace Prototype52
{
   // See the config file for more info.

   class TSecondaryPeerStrategyConfiguration :
      public TPeerStrategyBaseConfiguration
   {
#if( /* {public PositionConfiguration}. */ 1 )

      //
      public: TSecondaryPeerStrategyPositionConfiguration PositionConfiguration;

#endif
#if( /* {public OrdersPeerMessageReceiverConfiguration}. */ 1 )

      //
      public: TEconomicReportReceiverViaUdpConfiguration OrdersPeerMessageReceiverConfiguration;

#endif
#if( /* {public PlannedAction1PeerMessageReceiverConfiguration}. */ 1 )

      //
      public: TEconomicReportReceiverViaUdpConfiguration PlannedAction1PeerMessageReceiverConfiguration;

#endif
#if( /* {public PlannedAction2PeerMessageReceiverConfiguration}. */ 1 )

      //
      public: TEconomicReportReceiverViaUdpConfiguration PlannedAction2PeerMessageReceiverConfiguration;

#endif

#if( /* {(public)} Instance default constructor. */ 1 )

      // Could be autogenerated.

#endif
#if( /* //{(private)} Instance copy constructor. */ 1 )

      // Cannot be autogenerated.

#endif
#if( /* {(public)} Instance destructor. */ 1 )

      // Could be autogenerated.
      // {virtual}.

#endif
#if( /* //{(private) operator =}. */ 1 )

      // Cannot be autogenerated.

#endif

#if( /* {public Validate}. */ 1 )

      // yg? This might need a parameter specifying configuration extraction state. Or better add a method with that parameter to the helpers.
      // TODO 3 yg? If I implement this method I will need to make it {virtual}.

      public: void Validate() const;

#endif
   };
}
