#pragma once

//#include "./.hpp"

#include "../Common/SourceCodeModel/IncrementHeaderInclusionBalance.hpp"

namespace Prototype52
{
   // See the config file for more info.

   class TUntradableConditionConfiguration
   {
#if( /* {public EconomicReportValueMinLimit1}. */ 1 )

      //
      public: int EconomicReportValueMinLimit1;

#endif
#if( /* {public EconomicReportValueMaxLimit1}. */ 1 )

      //
      public: int EconomicReportValueMaxLimit1;

#endif
#if( /* {public EconomicReportValueMinLimit2}. */ 1 )

      //
      public: int EconomicReportValueMinLimit2;

#endif
#if( /* {public EconomicReportValueMaxLimit2}. */ 1 )

      //
      public: int EconomicReportValueMaxLimit2;

#endif

#if( /* {public} Instance default constructor. */ 1 )

      //

      public: explicit TUntradableConditionConfiguration();

#endif
#if( /* {private} Instance copy constructor. */ 1 )

      //

      private: explicit TUntradableConditionConfiguration
         ( TUntradableConditionConfiguration const & source
         );

#endif
#if( /* {public} Instance move constructor. */ 1 )

      //

      public: TUntradableConditionConfiguration
         ( TUntradableConditionConfiguration && source
         );

#endif
#if( /* {(public)} Instance destructor. */ 1 )

      // Could be autogenerated.

#endif
#if( /* {private operator =}. */ 1 )

      //

      private: TUntradableConditionConfiguration & operator =
         ( TUntradableConditionConfiguration const & source
         );

#endif
#if( /* {public operator =}. */ 1 )

      //

      public: TUntradableConditionConfiguration & operator =
         ( TUntradableConditionConfiguration && source
         );

#endif

#if( /* {public Assign}. */ 1 )

      // yg? Should this be named {Move}?

      public: void Assign
         ( TUntradableConditionConfiguration && source
         );

#endif

#if( /* {public Validate}. */ 1 )

      // yg? This might need a parameter specifying configuration extraction state. Or better add a method with that parameter to the helpers.

      public: void Validate() const;

#endif
   };
}
