#pragma once

#include "../TInstrumentDataSubscriptionBase.hpp"
#include "./TInstrumentTrade.hpp"

#include "../../Common/SourceCodeModel/IncrementHeaderInclusionBalance.hpp"

namespace Finance
{
namespace MarketData
{
   // There is no need to override the inherited {Prepare} method.

   template
      < typename TDerivedDataType_,
         typename TInstrument_
      >
   class TInstrumentTradeSubscriptionBase abstract :
      public TInstrumentDataSubscriptionBase< TDerivedDataType_, TInstrument_ >
   {
#if( /* {public InstrumentTrade}. */ 1 )

      // yg? Consider renaming this to {Data}.
      public: TInstrumentTrade InstrumentTrade;

#endif

#if( /* {protected} Instance default constructor. */ 1 )

      //

      protected: explicit TInstrumentTradeSubscriptionBase();

#endif
#if( /* //{(private)} Instance copy constructor. */ 1 )

      // Cannot be autogenerated.

#endif
#if( /* {(public)} Instance destructor. */ 1 )

      // Could be autogenerated.
      // This probably does not need to be {virtual}.

#endif
#if( /* //{(private) operator =}. */ 1 )

      // Cannot be autogenerated.

#endif

#if( /* //{public Unsubscribe>>>Async}. */ 1 )

      //>>>#pragma message( "yg---?? Consider moving this method to the base class." )
      //// yg? Rename this to {TrySendUnsubscriptionRequest} or {AsyncUnsubscribe}.
      //
      //public: void Unsubscribe>>>Async();

#endif
   };
}
}
