#pragma once

#include "./TREngineParamsConfiguration.hpp"
#include "./TLogInParamsConfiguration.hpp"
#include "./TInstrumentConfiguration.hpp"

#include "../Common/SourceCodeModel/IncrementHeaderInclusionBalance.hpp"

namespace RApiFacade
{
   // See the config file for more info.

   class TREngineAdapterConfiguration
   {
#if( /* {public REngineParamsConfiguration}. */ 1 )

      //
      public: TREngineParamsConfiguration REngineParamsConfiguration;

#endif
#if( /* {public LogInParamsConfiguration}. */ 1 )

      //
      public: TLogInParamsConfiguration LogInParamsConfiguration;

#endif
#if( /* {public InstrumentConfiguration}. */ 1 )

      //
      public: TInstrumentConfiguration InstrumentConfiguration;

#endif
#if( /* {public ShallSubscribeOrdersStateUpdate}. */ 1 )

      //
      public: bool ShallSubscribeOrdersStateUpdate;

#endif

#if( /* {public} Instance default constructor. */ 1 )

      //

      public: explicit TREngineAdapterConfiguration();

#endif
#if( /* {private} Instance copy constructor. */ 1 )

      //

      private: explicit TREngineAdapterConfiguration
         ( TREngineAdapterConfiguration const & source
         );

#endif
#if( /* {(public)} Instance destructor. */ 1 )

      // Could be autogenerated.

#endif
#if( /* {private operator =}. */ 1 )

      //

      private: TREngineAdapterConfiguration & operator =
         ( TREngineAdapterConfiguration const & source
         );

#endif

#if( /* {public Validate}. */ 1 )

      // yg? This might need a parameter specifying configuration extraction state. Or better add a method with that parameter to the helpers.

      public: void Validate() const;

#endif
   };
}
