#pragma once

#include "../../Common/ObjectModel/TDataSubscriptionBase.hpp"

#include "../../Common/SourceCodeModel/IncrementHeaderInclusionBalance.hpp"

namespace Finance
{
namespace Trading
{
   // TODO 3 yg? This class is a placeholder. Some members might need to be moved here from derived classes.
   // yg? We might need an even "basier" class for any orders, not only single instrument.
   // It's possible to derive this class from {TInstrumentDataSubscriptionBase<,>} but I don't like this idea.
   // The {TInstrumentDataSubscriptionBase<,>}, {TSingleInstrumentOrderBase<,>}, and {TOrderModificationRequestBase<,>}
   // classes are similar and some related comments repeat.

   template
      < typename TDerivedDataType_,
         typename TInstrument_
      >
   class TSingleInstrumentOrderBase abstract :
      public ::Common::ObjectModel::TDataSubscriptionBase< TDerivedDataType_ >
   {
#if( /* {private Instrument_}. */ 1 )

      // The constructor does not initialize this field.
      private: TInstrument_ const * Instrument_;

#endif

#if( /* {protected} Instance default constructor. */ 1 )

      //

      protected: explicit TSingleInstrumentOrderBase();

#endif
#if( /* //{(private)} Instance copy constructor. */ 1 )

      // Cannot be autogenerated.

#endif
#if( /* {(public)} Instance destructor. */ 1 )

      // Could be autogenerated.
      // This probably doesn't need to be {virtual}.

#endif
#if( /* //{(private) operator =}. */ 1 )

      // Cannot be autogenerated.

#endif

#if( /* {public Prepare}. */ 1 )

      // yg? Consider eliminating this method parameter and adding a {SetInstrument} method to be called before this one.
      // yg? Consider eliminating this method and passing its parameter to the constructor.
      // yg? But this refactoring is probably not urgent.
      // This probably doesn't need to be {virtual}.
      
      public: void Prepare
         ( TInstrument_ const & instrument1
         );

#endif

#if( /* {public Instrument}. */ 1 )

      //

      public: TInstrument_ const & Instrument() const;

#endif
   };
}
}
